src/Textarea.jsx, src/listener.js
=> Make listener work after unmount of single TextareaAutocomplete

.all-contributorsrc, .eslintrc, README.md, __tests__/__snapshots__/index.spec.js.snap, src/Item.jsx, src/List.jsx, src/Textarea.jsx, src/types.js
Issue #26 
I think it's ready. waiting feedback. :smile:
=> flow-types to type.js file

README.md, __tests__/__snapshots__/index.spec.js.snap, __tests__/index.spec.js, src/Item.jsx, src/List.jsx, src/Textarea.jsx, src/types.js, style.css
Now you can pass styles and class names for everything. 🤣 Close #32 #40
Fixed also #40
=> feat: you can pass styles and classnames

cypress/integration/textarea.js, example/App.jsx, src/Textarea.jsx
=> feat: dont show autocomplete when user keep typing

src/Textarea.jsx
When we match trigger char in the text ":" for example, we should return
the last possible occurence. Let's have a text "text:smile:good_smile" it this situation we should
return ":good_smile" not ":smile:good_smile"
CLOSE #61 #62
=> fix: take the last possible occurence of token

src/List.jsx, src/Textarea.jsx
=> Fix buggy behavior of `allowWhitespace`

__tests__/__snapshots__/index.spec.js.snap, src/Textarea.jsx
Fixed position of the autocomplete when the textarea is scrolled
CLOSE #86
=> fix(autocomplete): position autocomplete correctly 

src/Textarea.jsx
=> fix(textarea): update value correctly

__tests__/index.spec.js, cypress/integration/textarea.js, example/App.jsx, src/Textarea.jsx
This should solve #91 
Still highly in progress
=> Multichar triggers

src/Item.jsx
...to work properly on touch devices. 📱 
close #102
=> fix(item): Provide also onTouchStart event

example/index.html, src/Item.jsx, src/List.jsx
Attempt to fix #102 , tested on iOS only.
=> Allow handling of touch events, fix #102

src/Textarea.jsx, src/types.js
=> fix(trigger): fixed output function performance

cypress/integration/textarea.js, example/App.jsx, src/Textarea.jsx, webpack.prod.config.js
#100 #101 
This is the prototype of the new behavior which should solve the issues above.
I'd appreciate feedback from @guidogast
Example
=> New autocomplete behavior

__tests__/__snapshots__/index.spec.js.snap, src/Textarea.jsx
This commit adds the ability to recalculate the position of autocomplete based on dynamic height / weight
=> boundariesElement supports dynamic dimensions

src/Textarea.jsx, src/listener.js
=> Fix behaviour when autocomplete doenst show up in some cases

src/Textarea.jsx
=> fix(autocomplete): let's close the autocomple once selection is made

src/Textarea.jsx
Attempt to fix the bug, again :)
reference to PR #121 #120
I've apparently fixed in previous #121 another bug :)
=> This fix edge bug when you move to the other token by arrows

package.json, src/Textarea.jsx
=> Run Prettier in pre-commit hook

src/listener.js
Fixes #135 
I fixed index incrementing, also changed default index to 1, because otherwise comparisons like `if (this.escListener)` would not work with 0.
=> Fix listener index increment

cypress/integration/textarea.js, package.json, src/Textarea.jsx, yarn.lock
=> Fix autocomplete arrows behavior

cypress/integration/textarea.js, example/App.jsx, src/Textarea.jsx
Clean up last token position correctly in the case where a new multi-char token is introduced
CLOSE #145
=> fix: cleanup last token correctly

__tests__/__snapshots__/index.spec.js.snap, src/Item.jsx
This PR adds `.rta__item--selected` class in case item is selected. #153
=> feat(item): adds selected class for item container

src/Textarea.jsx
=> fix: correctly handle empty textareas

src/Textarea.jsx, src/types.js
=> fix: attach onBlur handler correctly

src/Textarea.jsx
close #194 
Ah, it looks I accidentally reformatted the code 🤦
=> fix: multichar tigger with allowWhitespace

src/Textarea.jsx
Closes #202
I accidentally shipped it in last release. #199
=> fix: remove console.log for debugging purpouses
